services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task-manager-network

  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: task_user
      DB_PASSWORD: task_password
      DB_NAME: task_manager
      SSL_MODE: disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - task-manager-network

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge