services:
  postgres:
    image: postgres:17-alpine
    container_name: taskmanager_db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - taskmanager_network

volumes:
  postgres_data:

networks:
  taskmanager_network:
    driver: bridge